language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  include:
  - python: "3.5"
    env: NEW_PIP=1
  - python: "3.3"
    env: ST_VER="==39.2.0"

script:
  # Upgrade to at least pip 10, to test against that as well
  - if [[ "$NEW_PIP" ]]; then pip install --upgrade "pip>=10" a; fi
  # Flake8 requires setuptools > 30, but some preinstalled are to old for that
  # Now 3.3 is not supported anymore, so use version 39.2.0 only there
  - pip install --upgrade setuptools$ST_VER
  - python setup.py test
  - coverage run setup.py test

notifications:
  email: false
before_install:
  - pip install codecov flake8
  - mkdir bad_tests
  - wget https://hg.python.org/cpython/archive/3.6.tar.bz2/Lib/test/ -O bad_tests/test.tar.bz2
  - tar -xjf bad_tests/test.tar.bz2 -C bad_tests/
  - mv bad_tests/cpython-*/Lib/test/badsyntax_future* . -v
  - rm -r bad_tests/
after_success:
  - codecov
